FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=development

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install --config.confirmModulesPurge=false

COPY . .

EXPOSE 8080

CMD ["pnpm", "dev"]