FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN corepack enable

RUN pnpm install --frozen-lockfile --prod

COPY . .

EXPOSE 8080

CMD ["node", "src/server.js"]