name: backend-clinica-prod
services:
  # ==========================================
  # SESIONES (REDIS)
  # ==========================================
  redis_clinica:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - network_backend_clinica

  # ==========================================
  # MONGO PRIMARY
  # ==========================================
  mongo_primary:
    image: mongo:7
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_primary_data:/data/db
    networks:
      - network_backend_clinica

  # ==========================================
  # MONGO SECONDARY 1
  # ==========================================
  mongo_secondary_1:
    image: mongo:7
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_secondary_1_data:/data/db
    networks:
      - network_backend_clinica

  # ==========================================
  # MONGO SECONDARY 2
  # ==========================================
  mongo_secondary_2:
    image: mongo:7
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_secondary_2_data:/data/db
    networks:
      - network_backend_clinica

  # ==========================================
  # MONGO REPLICA SET INIT
  # ==========================================
  mongo_setup:
    image: mongo:7
    restart: "no"

    depends_on:
      - mongo_primary
      - mongo_secondary_1
      - mongo_secondary_2

    entrypoint:
      - bash
      - -c
      - |
        echo "Esperando a MongoDB..."

        until mongosh --host mongo_primary --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
          sleep 2
        done

        echo "Inicializando Replica Set..."

        mongosh --host mongo_primary --eval '
          rs.initiate({
            _id: "rs0",
            members: [
              { _id: 0, host: "mongo_primary:27017", priority: 2 },
              { _id: 1, host: "mongo_secondary_1:27017", priority: 1 },
              { _id: 2, host: "mongo_secondary_2:27017", priority: 1 }
            ]
          });
        '

        echo "Replica Set inicializado."

    networks:
      - network_backend_clinica


  # ==========================================
  # MONOLITO NODE (CONTENEDOR 1)
  # ==========================================
  app_node_1:
    build:
      context: ..
      dockerfile: docker/dockerfile.prod
    environment:
      INSTANCE_NAME: app_node_1
    env_file:
      - .env.production
    depends_on:
      - mongo_setup
      - redis_clinica
    networks:
      - network_backend_clinica


  app_node_2:
    build:
      context: ..
      dockerfile: docker/dockerfile.prod
    environment:
      INSTANCE_NAME: app_node_2
    env_file:
      - .env.production
    depends_on:
      - mongo_setup
      - redis_clinica
    networks:
      - network_backend_clinica

  # ==========================================
  # PROMETHEUS
  # ==========================================

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - network_backend_clinica


  # ==========================================
  # GRAFANA
  # ==========================================

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - network_backend_clinica

  # ==========================================
  # NGINX(Balanceador)
  # ==========================================

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_node_1
      - app_node_2
    networks:
      - network_backend_clinica

# ==========================================
# CONFIGURACIÓN DE REDES Y VOLÚMENES
# ==========================================
networks:
  network_backend_clinica:
    driver: bridge

volumes:
  redis_data:
  mongo_primary_data:
  mongo_secondary_1_data:
  mongo_secondary_2_data:
  prometheus_data:
  grafana_data: