services:

  mongodb:
    image: mongo:7
    container_name: clinic-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: clinic-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ==========================================
  # MICROSERVICIO PDF
  # ==========================================
  pdf-service:
    build:
      context: ../pdf-service
      dockerfile: Dockerfile
    container_name: clinic-pdf-service
    volumes:
      - ../pdf-service:/app
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data:
  redis_data: